route:
  receiver: telegram
  group_wait: 0s
  group_interval: 30s
  repeat_interval: 1m

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: "1676633899:AAFWQ9T2DtHyPf70bSAcWxS8SGB5O3UUw5Q"
        chat_id: 577504834
        send_resolved: true
        message: "{{ .Status | toUpper }}: {{ .CommonAnnotations.summary }}"
