  - AutoPlace:
      - Dozzle:
          href: http://dozzle.127.0.0.1.sslip.io:8080
          description: Логи Docker
      - Админка:
          href: http://admin.autoplace.127.0.0.1.sslip.io:8080
          description: Filament
      - Клиент:
          href: http://autoplace.127.0.0.1.sslip.io:8080
          description: Внешний сайт
     
